<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>wavebench</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WaveBench.Core\WaveBench.Core.csproj" />
    <ProjectReference Include="..\WaveBench.Acoustics\WaveBench.Acoustics.csproj" />
    <ProjectReference Include="..\WaveBench.Boost\WaveBench.Boost.csproj" />
    <ProjectReference Include="..\WaveBench.Model\WaveBench.Model.csproj" />
    <ProjectReference Include="..\WaveBench.Analysis\WaveBench.Analysis.csproj" />
    <ProjectReference Include="..\WaveBench.Optimize\WaveBench.Optimize.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="ScottPlot" Version="5.1.59" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>
</Project>
