<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WaveBench.Core\WaveBench.Core.csproj" />
    <ProjectReference Include="..\WaveBench.Model\WaveBench.Model.csproj" />
    <ProjectReference Include="..\WaveBench.Acoustics\WaveBench.Acoustics.csproj" />
  </ItemGroup>
</Project>
